name: Shrine
description: Learn how to use Material for structure and layout.

dependencies:
  charts_flutter: ^0.6.0
  flutter:
    sdk: flutter
  intl: ^0.15.6

  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/diamond.png
    - packages/shrine_images/0-0.jpg
    - packages/shrine_images/1-0.jpg
    - assets/hotels/0.jpg
    - assets/hotels/1.jpg
    - assets/hotels/2.jpg
    - assets/hotels/3.jpg
    - assets/hotels/4.jpg
    - assets/hotels/5.jpg
    - assets/hotels/6.jpg
    - assets/hotels/7.jpg
    - assets/hotels/8.jpg
    - assets/hotels/9.jpg
    - assets/hotels/10.jpg
    - assets/hotels/11.jpg
    - assets/hotels/12.jpg
    - assets/hotels/13.jpg
    - assets/hotels/14.jpg
    - assets/hotels/15.jpg
    - assets/hotels/16.jpg
    - assets/hotels/17.jpg
    - assets/hotels/18.jpg
    - assets/hotels/19.jpg
    - assets/hotels/20.jpg
    - assets/hotels/21.jpg

